use_gpu: True
device: 0
early_stop:
  improve_indicator_mode: mean
  patience: 10
federate:
  mode: 'standalone'
  make_global_eval: False
  total_round_num: 400
  share_local_model: False
  data_weighted_aggr: True
data:
  root: data/
  type: graph_multi_domain_mol
  pre_transform: ["Constant", {"value": 1.0,  "cat": False}]
  transform:
    - [ "PadFeatures", { "target_dim": 37 } ]
    - [ "Constant",  { "value": 1.0, "cat": False } ]
personalization:
  local_param: ['clf']
dataloader:
  type: pyg
model:
  type: gin
  hidden: 64
  dropout: 0.5
  out_channels: 0
  task: graph
train:
  local_update_steps: 1
  optimizer:
    lr: 0.5
    weight_decay: 0.0005
    type: SGD
criterion:
  type: CrossEntropyLoss
trainer:
  type: graphminibatch_trainer
eval:
  freq: 5
  metrics: ['acc', 'correct']
