use_gpu: True
device: 0
early_stop:
  improve_indicator_mode: mean
  patience: 10
federate:
  mode: 'standalone'
  make_global_eval: False
  method: fedsak
  total_round_num: 400
  share_local_model: False
aggregator:
  lambda_: 2
  lr_shared: 1
  filter_keys: [""]
data:
  root: data/
  type: graph_multi_domain_mol
  pre_transform: ['Constant', {'value':1.0, 'cat':False}]
dataloader:
  type: pyg
model:
  type: gin
  hidden: 64
  dropout: 0.5
  out_channels: 0
  task: graph
train:
  local_update_steps: 30
  optimizer:
    lr: 0.5
    weight_decay: 0.0005
    type: SGD
criterion:
  type: CrossEntropyLoss
trainer:
  type: fedsak
eval:
  freq: 5
  metrics: ['acc', 'correct']
