use_gpu: True
device: 0
early_stop:
  improve_indicator_mode: mean
  patience: 20
federate:
  mode: 'standalone'
  make_global_eval: False
  method: fedsak
  client_num: 10
  total_round_num: 100
  share_local_model: False
aggregator:
  lambda_: 0.005
  lr_shared: 1
  filter_keys:
    - "encoder_atom.atom_embedding_list"
    - "gnn.convs.*.nn.linears"
    - "gnn.convs.*.nn.norms"
fedsak:
  share_patterns:
    - "encoder_atom.atom_embedding_list"
    - "gnn.convs.*.nn.linears"
    - "gnn.convs.*.nn.norms"
personalization:
  local_param:
    - "gnn.convs.*.eps"
    - "gnn.convs.*.nn.norms.*.running_mean"
    - "gnn.convs.*.nn.norms.*.running_var"
    - "gnn.convs.*.nn.norms.*.num_batches_tracked"
    - "linear"
    - "clf"
data:
  root: data/
  type: graph_multi_domain_mol
  pre_transform: ['Constant', {'value':1.0, 'cat':False}]
  transform:
    - [ "AddEdgeAttr", { } ]
    - [ "Constant",  { "value": 1.0, "cat": False } ]
dataloader:
  type: pyg
model:
  type: gin
  hidden: 64
  dropout: 0.5
  out_channels: 0
  task: graph
train:
  local_update_steps: 16
  optimizer:
    lr: 0.5
    weight_decay: 0.0005
    type: SGD
criterion:
  type: CrossEntropyLoss
trainer:
  type: fedsak
eval:
  freq: 5
  metrics: ['acc', 'correct']
