use_gpu: True
device: 0
early_stop:
  improve_indicator_mode: mean
  patience: 100
federate:
  mode: standalone
  total_round_num: 100
  method: gcflplus
data:
  root: data/
  type: graph_multi_domain_mol
  pre_transform: ['Constant', {'value':1.0, 'cat':False}]
dataloader:
  type: pyg
model:
  type: gin
  hidden: 64
  dropout: 0.5
  out_channels: 0
  task: graph
gcflplus:
  EPS_1: 0.05
  EPS_2: 0.1
  seq_length: 5
  standardize: False
train:
  local_update_steps: 8
  optimizer:
    lr: 0.5
    weight_decay: 0.0005
    type: SGD
criterion:
  type: CrossEntropyLoss
personalization:
  local_param: ['encoder_atom', 'encoder', 'clf']
trainer:
  type: graphminibatch_trainer
eval:
  freq: 5
  metrics: ['acc', 'correct']
