# ================================================================================
# CDA Minimal Config - BUS ERROR DEBUGGING
# ================================================================================
# 极简配置用于排查bus error问题
# 内存占用: <2GB
# ================================================================================

use_gpu: True
device: 1
backend: 'torch'
seed: 123

federate:
  mode: 'standalone'
  client_num: 10              # 最小化客户端数量
  sample_client_num: 5        # 最小化并发
  total_round_num: 10         # 先跑10轮测试
  method: 'cross_domain_adaptive'
  make_global_eval: True
  share_local_model: False
  online_aggr: False

data:
  root: '/root/data/PACS'
  type: 'pacs'
  splits: [0.8, 0.1, 0.1]
  dirichlet_alpha: 0.5        # 降低异构度，减少数据处理复杂度
  min_samples_per_client: 5
  server_test_samples_per_class: 10  # 减少server测试集

dataloader:
  batch_size: 4               # 极小batch
  shuffle: True
  num_workers: 0              # CRITICAL: 设为0避免多进程问题

model:
  type: 'cross_domain_adaptive'
  backbone: 'fedlsa_cnn'
  hidden: 128                 # 最小模型
  num_classes: 7
  dropout: 0.0
  out_channels: 7

train:
  local_update_steps: 1       # 最小化本地训练
  batch_or_epoch: 'epoch'
  optimizer:
    type: 'SGD'
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0005
  scheduler:
    type: 'StepLR'
    step_size: 5
    gamma: 0.1

eval:
  freq: 5                     # 减少评估频率
  metrics: ['acc']
  best_res_update_round_wise_key: 'test_acc'
  report: ['avg']
  split: ['test']

early_stop:
  patience: 0
  delta: 0.0
  improve_indicator_mode: 'best'

fedlsa:
  use: True
  lambda_com: 0.5
  tau: 0.1
  use_projector: True
  projector_input_dim: 128
  projector_output_dim: 64
  share_projector: True
  alpha_sep: 0.4
  anchor_train_epochs: 10     # 减少anchor训练
  anchor_lr: 0.001

ondemfl:
  enable: True
  pretrain_rounds: 5
  ondemand_rounds: 5
  subset_size: 5
  weight_scheme: 'ratio_times_size'
  min_ratio: 1e-4
  nnls_max_iter: 100
  nnls_tol: 1e-9
  dp_loss: 'kl'
  freeze_predictor_after_stage1: True
  dp_optimizer:
    type: 'SGD'
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0
    nesterov: False
  grad_layer: ''
  log_metrics: False          # 关闭额外日志
  target_distribution: []

cross_domain_adaptive:
  anchor_reweight: True
  anchor_weight_momentum: 0.6
  anchor_weight_eps: 1e-3

trainer:
  type: 'cross_domain_adaptive'

criterion:
  type: 'CrossEntropyLoss'

grad:
  grad_clip: 3.0
