
# 是否使用GPU以及设备号（True表示使用GPU）
use_gpu: True
device: 0

# --------------------------------------------------
# 1）联邦模式：Standalone + 单客户端
# --------------------------------------------------
federate:
  mode: standalone
  method: ditto            # 启用 Ditto
  client_num: 10
  total_round_num: 100
  data_weighted_aggr: False
  make_global_eval: False

personalization:
  local_update_steps: 10    # Ditto 本地迭代步数
  lr: 0.1                 # 本地个性化模型学习率（与 train.optimizer.lr 一致）
  regular_weight: 0.05      # 本地模型相对全局模型的正则系数

# --------------------------------------------------
# 2）数据集：Cora
# --------------------------------------------------
data:
  root: data/          # 相对于仓库根目录的 data 目录
  type: cora_pruned_globalval           # 指定使用 Cora

# --------------------------------------------------
# 3）Dataloader：PyG 全图
# --------------------------------------------------
dataloader:
  type: pyg
  batch_size: 1        # 全批次训练

# --------------------------------------------------
# 4）模型：GCN
# --------------------------------------------------
model:
  type: gcn
  hidden: 64
  dropout: 0.5
  out_channels: 7      # Cora 有 7 类
  layer: 1                 # GCN层数（两层GCN）

# --------------------------------------------------
# 5）损失与优化器
# --------------------------------------------------
criterion:
  type: CrossEntropyLoss

train:
  local_update_steps: 10  # 每轮只跑 1 步，全图梯度
  optimizer:
    type: SGD
    lr: 0.25
    weight_decay: 5e-4

# --------------------------------------------------
# 6）Trainer & Evaluator
# --------------------------------------------------
trainer:
  type: nodefullbatch_trainer

eval:
  freq: 1
  split: ['val','test']
  metrics: ['acc','loss']


