# --------------------------------------------------
# 1）联邦模式：Standalone + 单客户端
# --------------------------------------------------
federate:
  mode: standalone
  client_num: 5
  total_round_num: 200
  make_global_eval: True

# --------------------------------------------------
# 2）数据集：Cora
# --------------------------------------------------
data:
  root: data/          # 相对于仓库根目录的 data 目录
  type: cora           # 指定使用 Cora
  splitter: louvain    # 分割策略（单客户端下无影响，只要读入全图）


# --------------------------------------------------
# 3）Dataloader：PyG 全图
# --------------------------------------------------
dataloader:
  type: pyg
  batch_size: 1        # 全批次训练

# --------------------------------------------------
# 4）模型：GCN
# --------------------------------------------------
model:
  type: gcn
  hidden: 64
  dropout: 0.5
  out_channels: 7      # Cora 有 7 类
  layer: 2                 # GCN层数（两层GCN）

# --------------------------------------------------
# 5）损失与优化器
# --------------------------------------------------
criterion:
  type: CrossEntropyLoss

train:
  local_update_steps: 1  # 每轮只跑 1 步，全图梯度
  optimizer:
    type: SGD
    lr: 0.25
    weight_decay: 5e-4

# --------------------------------------------------
# 6）Trainer & Evaluator
# --------------------------------------------------
trainer:
  type: nodefullbatch_trainer

eval:
  freq: 1
  metrics: ['acc']

