# Cross-Domain Adaptive configuration for PACS (FIXED VERSION)
#
# FIXES:
# 1. Reduced client_num from 100 to 30 to prevent empty client data
# 2. Increased dirichlet_alpha from 0.1 to 0.5 for less extreme heterogeneity
# 3. Reduced server_test_samples_per_class from 40 to 30 to leave more data for clients
# 4. Reduced sample_client_num to match new client_num
#
# With these changes:
# - Each domain gets 7-8 clients (30 รท 4 domains)
# - More samples per client: ~180 train samples (vs ~103 before)
# - Less extreme heterogeneity: fewer clients will have 0 samples
#

use_gpu: True
device: 1
backend: 'torch'
seed: 123

federate:
  mode: 'standalone'
  client_num: 30  # CHANGED: 100 -> 30 (prevents empty clients)
  sample_client_num: 20  # CHANGED: 30 -> 20 (reduced proportionally)
  total_round_num: 200
  method: 'cross_domain_adaptive'
  make_global_eval: True
  share_local_model: False
  online_aggr: False

data:
  root: '/root/data/PACS'
  type: 'pacs'
  splits: [0.8, 0.1, 0.1]
  dirichlet_alpha: 0.5  # CHANGED: 0.1 -> 0.5 (less extreme heterogeneity)
  server_test_samples_per_class: 30  # CHANGED: 40 -> 30 (leaves more data for clients)

dataloader:
  batch_size: 8
  shuffle: True
  num_workers: 0

model:
  type: 'cross_domain_adaptive'
  backbone: 'fedlsa_cnn'
  hidden: 512
  num_classes: 7
  dropout: 0.0
  out_channels: 7

train:
  local_update_steps: 4
  batch_or_epoch: 'epoch'
  optimizer:
    type: 'SGD'
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0005
  scheduler:
    type: 'StepLR'
    step_size: 100
    gamma: 0.1

eval:
  freq: 1
  metrics: ['acc', 'loss']
  best_res_update_round_wise_key: 'test_acc'
  report: ['weighted_avg', 'avg', 'raw']
  split: ['test', 'val']

early_stop:
  patience: 0
  delta: 0.0
  improve_indicator_mode: 'best'

fedlsa:
  use: True
  lambda_com: 0.5
  tau: 0.1
  use_projector: True
  projector_input_dim: 512
  projector_output_dim: 256
  share_projector: True
  alpha_sep: 0.4
  anchor_train_epochs: 100
  anchor_lr: 0.001

ondemfl:
  enable: True
  pretrain_rounds: 150
  ondemand_rounds: 50
  subset_size: 20  # CHANGED: 30 -> 20 (match sample_client_num)
  weight_scheme: 'ratio_times_size'
  min_ratio: 1e-4
  nnls_max_iter: 500
  nnls_tol: 1e-9
  dp_loss: 'kl'
  freeze_predictor_after_stage1: True
  dp_optimizer:
    type: 'SGD'
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0
    nesterov: False
  grad_layer: ''
  log_metrics: True
  target_distribution: []

cross_domain_adaptive:
  anchor_reweight: True
  anchor_weight_momentum: 0.6
  anchor_weight_eps: 1e-3

trainer:
  type: 'cross_domain_adaptive'

criterion:
  type: 'CrossEntropyLoss'

grad:
  grad_clip: 5.0
