# ================================================================================
# FedAvg Configuration for PACS Dataset - MEMORY EFFICIENT & MATCHED
# ================================================================================
# This configuration matches the memory-efficient CDA config for fair comparison
#
# CRITICAL: All parameters MUST match the memory-efficient CDA config
#
# Memory Optimizations Applied:
# - batch_size: 16 (reduced from 48)
# - client_num: 40 (reduced from 60)
# - hidden: 384 (reduced from 512)
#
# Expected Result: FedAvg ~45% (baseline)
# Memory Usage: ~4-6GB (same as CDA)
# ================================================================================

use_gpu: True
device: 0                     # Different GPU for parallel execution
backend: 'torch'
seed: 123

# ========== Federate Settings ==========
federate:
  mode: 'standalone'
  client_num: 40              # MUST match CDA
  total_round_num: 250        # MUST match CDA
  method: 'fedavg_domain_eval'
  make_global_eval: True
  share_local_model: False
  online_aggr: False

# ========== Data Settings ==========
data:
  root: '/root/data/PACS'
  type: 'pacs'
  splits: [0.8, 0.1, 0.1]     # MUST match CDA
  dirichlet_alpha: 0.08       # MUST match CDA
  server_test_samples_per_class: 35  # MUST match CDA

# ========== DataLoader Settings ==========
dataloader:
  batch_size: 16              # MUST match CDA
  shuffle: True
  num_workers: 0

# ========== Model Settings ==========
model:
  type: 'fedlsa_cnn'          # MUST match CDA backbone
  hidden: 384                 # MUST match CDA
  num_classes: 7
  dropout: 0.1                # MUST match CDA
  out_channels: 7

# ========== Training Settings ==========
train:
  local_update_steps: 4       # MUST match CDA
  batch_or_epoch: 'epoch'
  optimizer:
    type: 'SGD'
    lr: 0.015                 # MUST match CDA
    momentum: 0.9
    weight_decay: 0.0005
  scheduler:
    type: 'CosineAnnealingLR' # MUST match CDA
    T_max: 250

# ========== Evaluation Settings ==========
eval:
  freq: 1
  metrics: ['acc', 'loss']
  best_res_update_round_wise_key: 'test_acc'
  report: ['weighted_avg', 'avg', 'raw']
  split: ['test', 'val']

# ========== Early Stopping ==========
early_stop:
  patience: 0
  delta: 0.0
  improve_indicator_mode: 'best'

# ========== Trainer & Loss ==========
trainer:
  type: 'general'             # Standard FedAvg

criterion:
  type: 'CrossEntropyLoss'

# ========== Gradient Clipping ==========
grad:
  grad_clip: 3.0              # MUST match CDA


# ================================================================================
# Memory Usage: ~4-6GB (same as CDA for fair comparison)
#
# Expected Performance:
# ================================================================================
# Round 250: ~45% accuracy
#   Photo:        ~50%
#   Art Painting: ~42%
#   Cartoon:      ~46%
#   Sketch:       ~40%
#
# Performance vs CDA: -20% (45% vs 65%)
# ================================================================================
