use_gpu: True
device: 0
seed: 1234
early_stop:
  patience: 0
federate:
  mode: standalone
  total_round_num: 500
  sample_client_rate: 1
  client_num: 25
data:
  root: data/
  type: shakespeare
  subsample: 0.2
  splits: [0.6,0.2,0.2]
  splitter: fedgs
  splitter_args: [{'alpha': 1}]
  consistent_label_distribution: False
dataloader:
  batch_size: 32
model:
  type: lstm
  in_channels: 80
  out_channels: 80
  embed_size: 8
  hidden: 256
  dropout: 0.0
train:
  local_update_steps: 1
  batch_or_epoch: epoch
  optimizer:
    lr: 0.8
    weight_decay: 0.0
criterion:
  type: CrossEntropyLoss
trainer:
  type: nlptrainer
eval:
  freq: 1
  metrics: ['acc', 'loss']
  best_res_update_round_wise_key: test_loss