# FedAvg Baseline with LDS (Label Distribution Skew) - Office-Home
# This is a fair comparison baseline for GGEUR_Clip with LDS:
# - Uses same CLIP features extraction
# - Uses same MLP classifier
# - Uses FedAvg aggregation
# - Uses Dirichlet distribution for non-IID data (alpha=0.1)
# - NO data augmentation (uses original imbalanced data)

# ========== Basic Settings ==========
use_gpu: True
device: 1
seed: 42
verbose: 1

# ========== Federated Learning Settings ==========
federate:
  method: 'ggeur'  # Use GGEUR_Clip infrastructure for CLIP feature extraction
  mode: 'standalone'
  client_num: 60  # One client per domain (required for LDS)
  total_round_num: 100
  sample_client_num: 60

# ========== Data Settings ==========
data:
  type: 'office-home'
  root: 'OfficeHomeDataset_10072016'
  splits: [0.7, 0.0, 0.3]

dataloader:
  batch_size: 16
  num_workers: 0

# ========== Model Settings ==========
model:
  type: 'ggeur_mlp'
  num_classes: 65

# ========== Training Settings ==========
train:
  local_update_steps: 1  # Paper uses 10 local epochs
  optimizer:
    type: 'Adam'
    lr: 0.001

# ========== GGEUR_Clip Settings (No Augmentation, but with LDS) ==========
ggeur:
  use: True

  # CLIP Feature Extraction (same as GGEUR_Clip)
  clip_model: 'ViT-B-16'
  clip_pretrained: 'openai'
  clip_model_path: '/root/model/open_clip_vitb16.bin'
  embedding_dim: 512

  # Feature Caching
  use_feature_cache: True
  feature_cache_dir: ''

  # === KEY DIFFERENCE: No Augmentation ===
  num_generated_per_sample: 0
  num_generated_per_prototype: 0
  target_size_per_class: 0

  # MLP Classifier (same as GGEUR_Clip)
  mlp_hidden_dim: 0
  mlp_dropout: 0.0

  # Disable cross-client prototype sharing
  use_cross_client_prototypes: False

  # Training Settings
  statistics_round: 0

  # ========== LDS Settings ==========
  use_lds: True
  lds_alpha: 0.1  # Paper default - creates highly skewed distribution
  lds_seed: 42

# ========== Output Settings ==========
outdir: 'exp/fedavg_officehome_lds_baseline/20percent'
expname: 'fedavg_lds_alpha0.1_no_augmentation'
