# ================================================================================
# FedAvg Configuration for PACS - MATCHED WITH PRACTICAL CDA CONFIG
# ================================================================================

use_gpu: True
device: 0
backend: 'torch'
seed: 123

# ========== Federate Settings ==========
federate:
  mode: 'standalone'
  client_num: 40              # MUST match CDA
  total_round_num: 300        # MUST match CDA
  method: 'fedavg_domain_eval'
  make_global_eval: True
  share_local_model: False
  online_aggr: False

# ========== Data Settings ==========
data:
  root: '/root/data/PACS'
  type: 'pacs'
  splits: [0.8, 0.1, 0.1]
  dirichlet_alpha: 0.3        # MUST match CDA
  server_test_samples_per_class: 30  # MUST match CDA

# ========== DataLoader Settings ==========
dataloader:
  batch_size: 16              # MUST match CDA
  shuffle: True
  num_workers: 0

# ========== Model Settings ==========
model:
  type: 'fedlsa_cnn'
  hidden: 512                 # MUST match CDA
  num_classes: 7
  dropout: 0.1                # MUST match CDA
  out_channels: 7

# ========== Training Settings ==========
train:
  local_update_steps: 5       # MUST match CDA
  batch_or_epoch: 'epoch'
  optimizer:
    type: 'SGD'
    lr: 0.01                  # MUST match CDA
    momentum: 0.9
    weight_decay: 0.0005
  scheduler:
    type: 'StepLR'            # MUST match CDA
    step_size: 100
    gamma: 0.1

# ========== Evaluation Settings ==========
eval:
  freq: 1
  metrics: ['acc', 'loss']
  best_res_update_round_wise_key: 'test_acc'
  report: ['weighted_avg', 'avg', 'raw']
  split: ['test', 'val']

# ========== Early Stopping ==========
early_stop:
  patience: 0
  delta: 0.0
  improve_indicator_mode: 'best'

# ========== Trainer & Loss ==========
trainer:
  type: 'general'

criterion:
  type: 'CrossEntropyLoss'

# ========== Gradient Clipping ==========
grad:
  grad_clip: 5.0              # MUST match CDA


# ================================================================================
# 预期性能:
# ================================================================================
# Round 300: ~42-45%
#   Photo:        ~48%
#   Art Painting: ~40%
#   Cartoon:      ~44%
#   Sketch:       ~38%
#   Weighted Avg: ~43%
#
# 对比CDA: CDA应高出10-15% (57% vs 43%)
# ================================================================================
