# Simplified FedLSA Configuration
# Basic settings
use_gpu: False
device: -1
backend: 'torch'
seed: 123

# Federate settings
federate:
  mode: 'standalone'
  client_num: 5
  total_round_num: 10
  sample_client_num: 5
  make_global_eval: False
  share_local_model: False
  online_aggr: False

# Data settings
data:
  root: 'data/'
  type: 'FEMNIST'
  splits: [0.8, 0.1, 0.1]

# Model settings
model:
  type: 'convnet2'
  hidden: 512
  num_classes: 62
  out_channels: 512

# Training settings
train:
  local_update_steps: 1
  batch_or_epoch: 'epoch'
  optimizer:
    type: 'SGD'
    lr: 0.01
    momentum: 0.9

# Evaluation settings
eval:
  freq: 2
  metrics: ['acc']
  best_res_update_round_wise_key: 'test_acc'

# FedLSA specific settings
fedlsa:
  use: True
  lambda_com: 0.5
  tau: 0.1
  use_projector: True
  projector_input_dim: 2048
  projector_output_dim: 128
  share_projector: True
  alpha_sep: 0.4
  anchor_train_epochs: 50
  anchor_lr: 0.001

# Trainer type
trainer:
  type: 'fedlsa_trainer'

# Criterion
criterion:
  type: 'CrossEntropyLoss'

# Output
outdir: 'exp_fedlsa_test'
expname: 'test_run'
