use_gpu: True
device: 0
early_stop:
  patience: 20
  delta: 0.0

federate:
  mode: standalone
  client_num: 4  # 4 domains: Amazon, Webcam, DSLR, Caltech
  sample_client_num: 4
  total_round_num: 100
  share_local_model: True
  online_aggr: False
  make_global_eval: False

data:
  root: data/
  type: 'office_caltech_10@torchvision'
  splits: [0.8, 0.1, 0.1]

dataloader:
  type: base
  batch_size: 32
  shuffle: True
  num_workers: 0

model:
  type: 'resnet18'
  num_classes: 10
  out_channels: 512

trainer:
  type: 'fedproto_trainer'

train:
  optimizer:
    type: 'SGD'
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0005
  local_update_steps: 10
  batch_or_epoch: epoch

eval:
  freq: 5
  metrics: ['acc', 'correct']
  best_res_update_round_wise_key: test_acc

criterion:
  type: 'CrossEntropyLoss'

fedproto:
  use: True
  proto_weight: 1.0
  embedding_dim: 512
  use_projector: True
  projector_hidden_dim: 256
  distance_metric: 'cosine'
  temperature: 0.1
  aggregation_method: 'weighted_mean'
  local_proto_epochs: 1
  normalize_prototypes: True
  freeze_backbone: False

seed: 12345
