use_gpu: True
device: 0
early_stop:
  patience: 20
  delta: 0.0

federate:
  mode: standalone
  client_num: 10
  sample_client_num: 10
  total_round_num: 50
  share_local_model: True
  online_aggr: False
  make_global_eval: False

data:
  root: data/
  type: 'CIFAR10@torchvision'
  splits: [0.6, 0.2, 0.2]
  subsample: 1.0
  splitter: 'lda'
  splitter_args: [{'alpha': 0.5}]

dataloader:
  type: base
  batch_size: 32
  shuffle: True

model:
  type: 'convnet2'
  hidden: 256
  num_classes: 10
  dropout: 0.1

trainer:
  type: 'fedproto_trainer'

train:
  optimizer:
    type: 'SGD'
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0005
  local_update_steps: 10
  batch_or_epoch: epoch

eval:
  freq: 5
  metrics: ['acc', 'correct']
  best_res_update_round_wise_key: test_acc

criterion:
  type: 'CrossEntropyLoss'

fedproto:
  use: True
  proto_weight: 1.0
  embedding_dim: 256
  use_projector: False
  projector_hidden_dim: 128
  distance_metric: 'euclidean'
  temperature: 0.5
  aggregation_method: 'mean'
  local_proto_epochs: 1
  normalize_prototypes: False
  freeze_backbone: False

seed: 12345
