# GGEUR_Clip with LDS (Label Distribution Skew) - Office-Home
# This configuration matches the paper's experimental setup:
# - 4 clients (one per domain)
# - Dirichlet distribution for non-IID data (alpha=0.1)
# - Each client only has a portion of each class's data

# ========== Basic Settings ==========
use_gpu: True
device: 1
seed: 42
verbose: 1

# ========== Federated Learning Settings ==========
federate:
  method: 'ggeur'
  mode: 'standalone'
  client_num: 60 # One client per domain (required for LDS)
  total_round_num: 100
  sample_client_num: 60


# ========== Data Settings ==========
data:
  type: 'office-home'
  root: 'OfficeHomeDataset_10072016'
  splits: [0.7, 0.0, 0.3]  # train, val, test ratios

dataloader:
  batch_size: 16
  num_workers: 0

# ========== Model Settings ==========
model:
  type: 'ggeur_mlp'
  num_classes: 65

# ========== Training Settings ==========
train:
  local_update_steps: 1  # Paper uses 10 local epochs
  optimizer:
    type: 'Adam'
    lr: 0.001

# ========== GGEUR_Clip Specific Settings ==========
ggeur:
  use: True

  # CLIP Feature Extraction
  clip_model: 'ViT-B-16'
  clip_pretrained: 'openai'
  clip_model_path: '/root/model/open_clip_vitb16.bin'
  embedding_dim: 512

  # Feature Caching
  use_feature_cache: True
  feature_cache_dir: ''

  # Feature Augmentation
  num_generated_per_sample: 50
  num_generated_per_prototype: 50
  target_size_per_class: 50

  # MLP Classifier (linear, no hidden layer - matches paper)
  mlp_hidden_dim: 0
  mlp_dropout: 0.0

  # Multi-domain Settings
  use_cross_client_prototypes: True

  # Training Settings
  statistics_round: 0

  # ========== LDS Settings (KEY DIFFERENCE) ==========
  use_lds: True
  lds_alpha: 0.1  # Paper default - creates highly skewed distribution
  lds_seed: 42

# ========== Output Settings ==========
outdir: 'exp/ggeur_officehome_lds/20percent'
expname: 'ggeur_lds_alpha0.1'
