# GGEUR_Clip with Separated Training - Office-Home LDS
#
# Separated Training Mode:
# ========================
# Phase 1 (Rounds 1-20): Train classifier on GGEUR_Clip augmented features
#   - Classifier learns from rich augmented data with cross-domain information
#   - Benefits from GGEUR_Clip's Gaussian feature expansion
#
# Phase 2 (Rounds 21-100): Train CNN backbone with frozen classifier
#   - CNN backbone trained FROM SCRATCH (no pretrained weights)
#   - Classifier is FROZEN - only backbone learns
#   - CNN learns to produce features that work with the trained classifier
#   - Feature alignment with CLIP is CRITICAL for good performance
#
# Key Insight:
#   The classifier defines "what good features look like"
#   The CNN backbone learns to produce such features from images
#
# Loss in Phase 2:
#   L = CE(frozen_classifier(backbone(x)), y) + λ * MSE(CNN_feat, CLIP_feat)

# ========== Basic Settings ==========
use_gpu: True
device: 1
seed: 42
verbose: 1

# ========== Federated Learning Settings ==========
federate:
  method: 'ggeur'
  mode: 'standalone'
  client_num: 4  # One client per domain (Art, Clipart, Product, Real_World)
  total_round_num: 100  # Phase 1: 20 rounds, Phase 2: 80 rounds
  sample_client_num: 4

# ========== Data Settings ==========
data:
  type: 'office-home'
  root: 'OfficeHomeDataset_10072016'
  splits: [0.7, 0.0, 0.3]

dataloader:
  batch_size: 32
  num_workers: 0

# ========== Model Settings ==========
model:
  type: 'ggeur_mlp'
  num_classes: 65

# ========== Training Settings ==========
train:
  local_update_steps: 10
  optimizer:
    type: 'Adam'
    lr: 0.001

# ========== GGEUR_Clip Specific Settings ==========
ggeur:
  use: True

  # CLIP Feature Extraction
  clip_model: 'ViT-B-16'
  clip_pretrained: 'openai'
  clip_model_path: '/root/model/open_clip_vitb16.bin'  # Local path
  embedding_dim: 512

  # Feature Caching
  use_feature_cache: True
  feature_cache_dir: ''

  # Feature Augmentation (for classifier training in Phase 1)
  num_generated_per_sample: 50
  num_generated_per_prototype: 50
  target_size_per_class: 50

  # MLP Classifier (used in Phase 1, frozen in Phase 2)
  mlp_hidden_dim: 0  # Linear classifier: 512 -> 65
  mlp_dropout: 0.0

  # Multi-domain Settings
  use_cross_client_prototypes: True

  # Training Settings
  statistics_round: 0

  # LDS Settings
  use_lds: True
  lds_alpha: 0.1
  lds_seed: 42

  # ========== Separated Training Settings ==========
  use_separated_training: True

  # Phase 1: Classifier pre-training rounds
  # After these rounds, transition to Phase 2 (CNN backbone training)
  classifier_pretrain_rounds: 20

  # Freeze classifier in Phase 2
  freeze_classifier: True

  # CNN backbone architecture
  cnn_model: 'resnet18'  # Options: resnet18, resnet34, resnet50, mobilenet_v2

  # CNN training settings (for Phase 2) - 防止过拟合的推荐设置
  cnn_lr: 0.01  # 提高学习率，加快收敛
  cnn_local_epochs: 5  # 适中的本地轮次
  cnn_weight_decay: 1e-4  # 适度正则化
  cnn_use_augmentation: False  # 暂时禁用数据增强进行调试

  # Feature alignment settings (CRITICAL for good test accuracy)
  align_weight: 1.0  # 对齐权重

  # Disable other CNN modes (mutually exclusive with separated training)
  use_cnn_distillation: False
  use_feature_alignment: False

# ========== Output Settings ==========
outdir: 'exp/ggeur_separated_training'
expname: 'ggeur_separated_officehome'
