# GGEUR_Clip with Separated Training - PACS
#
# PACS Dataset: 4 domains (Photo, Art Painting, Cartoon, Sketch)
# 7 classes: dog, elephant, giraffe, guitar, horse, house, person
#
# Separated Training Mode:
# Phase 1: Train classifier on GGEUR_Clip augmented features (20 rounds)
# Phase 2: Train CNN backbone with frozen classifier (80 rounds)

# ========== Basic Settings ==========
use_gpu: True
device: 0
seed: 42
verbose: 1

# ========== Federated Learning Settings ==========
federate:
  method: 'ggeur'
  mode: 'standalone'
  client_num: 4
  total_round_num: 100
  sample_client_num: 4

# ========== Data Settings ==========
data:
  type: 'pacs'
  root: 'data/PACS'
  splits: [0.8, 0.1, 0.1]

dataloader:
  batch_size: 32
  num_workers: 0

# ========== Model Settings ==========
model:
  type: 'ggeur_mlp'
  num_classes: 7

# ========== Training Settings ==========
train:
  local_update_steps: 10
  optimizer:
    type: 'Adam'
    lr: 0.001

# ========== GGEUR_Clip Specific Settings ==========
ggeur:
  use: True

  # CLIP Feature Extraction
  clip_model: 'ViT-B-16'
  clip_pretrained: 'openai'
  clip_model_path: '/root/model/open_clip_vitb16.bin'
  embedding_dim: 512

  # Feature Caching
  use_feature_cache: True
  feature_cache_dir: ''

  # Feature Augmentation
  num_generated_per_sample: 50
  num_generated_per_prototype: 50
  target_size_per_class: 50

  # MLP Classifier
  mlp_hidden_dim: 0
  mlp_dropout: 0.0

  # Multi-domain Settings
  use_cross_client_prototypes: True

  # Training Settings
  statistics_round: 0

  # LDS Settings
  use_lds: True
  lds_alpha: 0.1
  lds_seed: 42

  # ========== Separated Training Settings ==========
  use_separated_training: True
  classifier_pretrain_rounds: 20
  freeze_classifier: True

  # CNN settings
  cnn_model: 'resnet18'
  cnn_lr: 0.01
  cnn_local_epochs: 10

  # Disable other modes
  use_cnn_distillation: False
  use_feature_alignment: False

# ========== Output Settings ==========
outdir: 'exp/ggeur_separated_training_pacs'
expname: 'ggeur_separated_pacs'
