"""
Configuration for GGEUR_Clip on PACS dataset (Multi-Domain Scenario)

PACS dataset has 4 domains:
- Photo (P): 1,670 images
- Art Painting (AP): 2,048 images
- Cartoon (Ct): 2,344 images
- Sketch (Sk): 3,929 images

Each domain has 7 classes.

Expected results (Table 6 in paper):
- P: ~99.4%
- AP: ~98.4%
- Ct: ~99.0%
- Sk: ~93.6%
- Average: ~97.6%
"""

use_gpu: True
device: 0

# Federated learning setup
federate:
  mode: 'standalone'
  total_round_num: 50
  client_num: 4  # 4 domains
  sample_client_num: 4
  make_global_eval: False
  method: 'ggeur'

# Data configuration
data:
  root: 'data/'
  type: 'PACS'
  splits: [0.3, 0.0, 0.0]  # Use 30% of each domain
  splitter: 'domain'
  batch_size: 16

dataloader:
  batch_size: 16
  num_workers: 0

# Model configuration
model:
  type: 'mlp'
  num_classes: 7

# Training configuration
train:
  local_update_steps: 10
  batch_or_epoch: 'epoch'

  optimizer:
    type: 'Adam'  # Paper uses Adam
    lr: 0.001  # PACS uses lr=0.001
    weight_decay: 0.0

# GGEUR_Clip configuration
ggeur:
  use: True
  scenario: 'multi_domain'

  clip_model: 'ViT-B/16'
  embedding_dim: 512
  cache_embeddings: True

  # Paper's augmentation parameters for PACS
  # Based on Digits implementation (closest to PACS in the source code)
  n_samples_per_original: 12  # Generate 12 samples per original
  m_samples_per_prototype: 500  # Generate 500 samples per other-domain prototype
  step1_samples_per_class: 500  # Target 500 samples after Step 1

  # CRITICAL: Use paper's full covariance method
  use_full_covariance: True  # Use full covariance matrix (not diagonal approximation)
  eigenvalue_scaling: True  # Scale top 10 eigenvalues by [5.0, 4.5, ..., 1.0]

  # Target distribution settings (NEW FEATURE)
  # If specified, GGEUR_Clip will generate data according to this distribution
  # If null, uses uniform distribution (default)
  target_distribution: null  # Example: [0.1, 0.15, 0.1, 0.15, 0.2, 0.15, 0.15] for 7 classes
  total_samples_after_augmentation: null  # Total samples after augmentation (null = auto)

  # Example: Imbalanced distribution for PACS (7 classes)
  # target_distribution: [0.05, 0.1, 0.15, 0.2, 0.2, 0.15, 0.15]
  # This will create: Class 0: 5%, Class 1: 10%, Class 2: 15%, etc.

  mlp_layers: 1
  mlp_hidden_dim: 512

# Evaluation
eval:
  freq: 5
  metrics: ['acc']
  best_res_update_round_wise_key: 'test_acc'  # Use 'test_acc' to match metric keys
  split: ['test']  # Evaluate on test split

# Early stopping configuration
early_stop:
  patience: 50
  delta: 0.0
  improve_indicator_mode: 'best'

trainer:
  type: 'ggeur'

outdir: 'exp/ggeur_pacs_multi_domain'
expname: 'ggeur_pacs'
seed: 12345
