"""
Configuration file for GGEUR_Clip on Digits dataset (Multi-Domain Scenario)

This configuration reproduces the multi-domain experiments from the GGEUR_Clip paper
on the Digits dataset (MNIST, USPS, SVHN, SYN).

Expected results (Table 4 in paper):
- MNIST: ~97%
- USPS: ~94%
- SVHN: ~63%
- SYN: ~75%
- Average: ~82%
"""

use_gpu: True
device: 0

early_stop:
  patience: 50

# Federated learning setup
federate:
  mode: 'standalone'
  total_round_num: 50  # Paper uses 50 rounds
  client_num: 4  # 4 domains
  sample_client_num: 4  # All clients participate
  make_global_eval: False
  method: 'ggeur'  # Use GGEUR_Clip method

# Data configuration
data:
  root: 'data/'
  type: 'Digits'  # MNIST, USPS, SVHN, SYN
  splits: [0.1, 0.0, 0.0]  # Use 10% of each domain (as per paper)
  splitter: 'domain'  # Each client gets one domain
  batch_size: 16

dataloader:
  batch_size: 16
  num_workers: 0

# Model configuration
model:
  type: 'mlp'
  num_classes: 10

# Training configuration
train:
  local_update_steps: 10  # Epochs per round
  batch_or_epoch: 'epoch'

  optimizer:
    type: 'Adam'  # Paper uses Adam
    lr: 0.01
    weight_decay: 0.0

# GGEUR_Clip specific configuration
ggeur:
  use: True
  scenario: 'multi_domain'  # Multi-domain scenario

  # CLIP settings
  clip_model: 'ViT-B/16'
  embedding_dim: 512
  cache_embeddings: True

  # Augmentation parameters (as per paper)
  n_samples_per_original: 10  # N in Algorithm 2
  m_samples_per_prototype: 500  # M in Algorithm 2
  step1_samples_per_class: 500  # Target for Step 1

  # Geometric shape
  top_k_eigenvalues: null  # Use all eigenvalues
  cov_regularization: 1e-6

  # MLP classifier
  mlp_layers: 1  # Single layer MLP (paper uses simple classifier)
  mlp_hidden_dim: 512
  mlp_dropout: 0.0

  # Workflow
  upload_statistics_round: 0  # Round 0: collect statistics
  start_augmentation_round: 1  # Round 1+: train with augmentation

# Evaluation configuration
eval:
  freq: 5  # Evaluate every 5 rounds
  metrics: ['acc']
  best_res_update_round_wise_key: 'test_acc'  # Use 'test_acc' to match metric keys
  split: ['test']  # Evaluate on test split

# Trainer type
trainer:
  type: 'ggeur'

# Output configuration
outdir: 'exp/ggeur_digits_multi_domain'
expname: 'ggeur_digits'
seed: 12345
