data:
  batch_size: 16
  root: OfficeHomeDataset_10072016/
  splits:
  - 0.8
  - 0.1
  - 0.1
  splitter: lda_domain
  splitter_args:
  - alpha: 0.1
  type: OfficeHome
dataloader:
  batch_size: 16
  num_workers: 0
device: 1
early_stop:
  delta: 0.0
  improve_indicator_mode: best
  patience: 50
eval:
  best_res_update_round_wise_key: test_acc
  freq: 1
  metrics:
  - acc
  split:
  - test
expname: ggeur_officehome_beta0.1_fixed
federate:
  client_num: 4
  make_global_eval: false
  method: ggeur
  mode: standalone
  sample_client_num: 4
  total_round_num: 50
ggeur:
  cache_embeddings: true
  clip_model: ViT-B/16
  eigenvalue_scaling: true
  embedding_dim: 512
  m_samples_per_prototype: 50
  mlp_hidden_dim: 512
  mlp_layers: 1
  n_samples_per_original: 50
  scenario: multi_domain
  step1_samples_per_class: 50
  target_distribution: null
  total_samples_after_augmentation: null
  use: true
  use_full_covariance: true
model:
  num_classes: 65
  type: mlp
outdir: exp/ggeur_officehome_lds_fixed
seed: 12345
train:
  batch_or_epoch: epoch
  local_update_steps: 10  # FIXED: 从1增加到10，让模型有足够的训练
  optimizer:
    lr: 0.001
    type: Adam
    weight_decay: 0.0
trainer:
  type: ggeur
use_gpu: true
