# GGEUR_Clip with CNN Feature Extractor (ConvNeXt-Base) - PACS Dataset
#
# Uses ConvNeXt-Base for feature extraction on PACS dataset.
# PACS has 4 domains: Photo, Art_Painting, Cartoon, Sketch
#
# Expected Performance (Reference):
# - CLIP ViT-B-16: ~85-90% average accuracy
# - ConvNeXt-Base: ~80-85% average accuracy (competitive)
#
# Note: ConvNeXt may have slightly lower cross-domain generalization
# than CLIP due to CLIP's text-image training, but provides:
# - No dependency on open_clip library
# - Faster inference
# - Same model for training and deployment

# ========== Basic Settings ==========
use_gpu: True
device: 0
seed: 42
verbose: 1

# ========== Federated Learning Settings ==========
federate:
  method: 'ggeur'
  mode: 'standalone'
  client_num: 4  # photo, art_painting, cartoon, sketch
  total_round_num: 50
  sample_client_num: 4

# ========== Data Settings ==========
data:
  type: 'pacs'
  root: 'PACS'
  splits: [0.8, 0.0, 0.2]  # 80% train, 0% val, 20% test

dataloader:
  batch_size: 32
  num_workers: 0

# ========== Model Settings ==========
model:
  type: 'ggeur_mlp'
  num_classes: 7  # PACS has 7 classes

# ========== Training Settings ==========
train:
  local_update_steps: 10
  optimizer:
    type: 'Adam'
    lr: 0.001

# ========== GGEUR_Clip Specific Settings ==========
ggeur:
  use: True

  # ===== Feature Extractor Mode =====
  feature_extractor: 'cnn'

  # ===== CNN Feature Extractor Settings =====
  cnn_backbone: 'convnext_base'
  cnn_pretrained: True
  freeze_backbone: True

  # ===== Feature Dimension (ConvNeXt-Base: 1024) =====
  embedding_dim: 1024

  # ===== Feature Caching =====
  use_feature_cache: True
  feature_cache_dir: ''

  # ===== Feature Augmentation =====
  num_generated_per_sample: 50
  num_generated_per_prototype: 50
  target_size_per_class: 100

  # ===== MLP Classifier =====
  mlp_hidden_dim: 0
  mlp_dropout: 0.0

  # ===== Multi-domain Settings =====
  use_cross_client_prototypes: True

  # ===== Training Settings =====
  statistics_round: 0

  # ===== LDS Settings (Optional) =====
  use_lds: False
  lds_alpha: 0.1
  lds_seed: 42

  # ===== Disable other CNN modes =====
  use_cnn_distillation: False
  use_feature_alignment: False
  use_separated_training: False

# ========== Output Settings ==========
outdir: 'exp/ggeur_cnn_pacs'
expname: 'ggeur_cnn_pacs'
