# GGEUR_Clip with CNN Feature Alignment - PACS
# This configuration trains CNN FROM SCRATCH by aligning features with CLIP
#
# PACS Dataset: 4 domains (Photo, Art Painting, Cartoon, Sketch)
# 7 classes: dog, elephant, giraffe, guitar, horse, house, person
#
# Training flow:
# 1. Extract CLIP features and compute local statistics (Round 0)
# 2. Server aggregates covariances and computes global prototypes
# 3. Clients perform feature augmentation and train MLP
# 4. Clients train CNN from scratch with feature alignment loss

# ========== Basic Settings ==========
use_gpu: True
device: 0
seed: 42
verbose: 1

# ========== Federated Learning Settings ==========
federate:
  method: 'ggeur'
  mode: 'standalone'
  client_num: 4  # One client per domain
  total_round_num: 100
  sample_client_num: 4

# ========== Data Settings ==========
data:
  type: 'pacs'
  root: 'data/PACS'
  splits: [0.8, 0.1, 0.1]

dataloader:
  batch_size: 32
  num_workers: 0

# ========== Model Settings ==========
model:
  type: 'ggeur_mlp'
  num_classes: 7

# ========== Training Settings ==========
train:
  local_update_steps: 10
  optimizer:
    type: 'Adam'
    lr: 0.001

# ========== GGEUR_Clip Specific Settings ==========
ggeur:
  use: True

  # CLIP Feature Extraction
  clip_model: 'ViT-B-16'
  clip_pretrained: 'openai'
  clip_model_path: '/root/model/open_clip_vitb16.bin'
  embedding_dim: 512

  # Feature Caching
  use_feature_cache: True
  feature_cache_dir: ''

  # Feature Augmentation
  num_generated_per_sample: 50
  num_generated_per_prototype: 50
  target_size_per_class: 50

  # MLP Classifier
  mlp_hidden_dim: 0
  mlp_dropout: 0.0

  # Multi-domain Settings
  use_cross_client_prototypes: True

  # Training Settings
  statistics_round: 0

  # LDS Settings
  use_lds: True
  lds_alpha: 0.1
  lds_seed: 42

  # ========== CNN Feature Alignment Settings ==========
  use_feature_alignment: True
  use_cnn_distillation: False

  # CNN model
  cnn_model: 'resnet18'

  # Feature alignment parameters
  align_weight: 1.0
  use_prototype_alignment: True
  prototype_align_weight: 0.5

  # CNN training settings
  cnn_lr: 0.01
  cnn_local_epochs: 10
  cnn_warmup_rounds: 5

# ========== Output Settings ==========
outdir: 'exp/ggeur_cnn_feature_alignment_pacs'
expname: 'ggeur_feature_align_pacs'
