
# 是否使用GPU以及设备号（True表示使用GPU）
use_gpu: True
device: 0

early_stop:
  patience: 10

# --------------------------------------------------
# 1）联邦模式：Standalone + 单客户端
# --------------------------------------------------
federate:
  mode: standalone
  client_num: 1
  total_round_num: 500
  data_weighted_aggr: False
  make_global_eval: True


# --------------------------------------------------
# 2）数据集：Cora
# --------------------------------------------------
data:
  root: data/          # 相对于仓库根目录的 data 目录
  type: squirrel_disconnected           # 指定使用 Cora

# --------------------------------------------------
# 3）Dataloader：PyG 全图
# --------------------------------------------------
dataloader:
  type: pyg
  batch_size: 1        # 全批次训练

# --------------------------------------------------
# 4）模型：GCN
# --------------------------------------------------
model:
  type: gcn
  hidden: 128
  dropout: 0.5
  out_channels: 5
  layer: 2                 # GCN层数（两层GCN）

# --------------------------------------------------
# 5）损失与优化器
# --------------------------------------------------
criterion:
  type: CrossEntropyLoss

train:
  local_update_steps: 5  # 每轮只跑 1 步，全图梯度
  optimizer:
    type: Adam
    lr: 0.0001
    weight_decay: 0.001

# --------------------------------------------------
# 6）Trainer & Evaluator
# --------------------------------------------------
trainer:
  type: nodefullbatch_trainer

eval:
  freq: 1
  split: ['val','test']
  metrics: ['acc','loss']


