use_gpu: True
device: 0
early_stop:
  patience: 10
seed: 12345
federate:
  mode: standalone
  total_round_num: 500
  sample_client_rate: 1
  client_num: 10
data:
  root: data/
  type: ut_har
  # splits: [0.8,0.1,0.1]
  # splitter: ut_har_splitter
  splitter: lda
  splitter_args: [{'alpha': 0.5}]
dataloader:
  batch_size: 32
model:
  type: rnn
  out_channels: 7
train:
  local_update_steps: 5
  batch_or_epoch: epoch
  optimizer:
    type: Adam
    lr: 0.0005
    weight_decay: 0.01
grad:
  grad_clip: 5.0
criterion:
  type: CrossEntropyLoss
# trainer:
#   type: ut_har_rnn_trainer
eval:
  freq: 1
  metrics: ['acc', 'loss']
  best_res_update_round_wise_key: test_loss
# wandb:
#   use: True
#   name_project: ut_har_rnn
#   name_user: 2237617390-

