use_gpu: True
device: 0
seed: 12345
early_stop:
  patience: 0
federate:
  mode: standalone
  total_round_num: 100
  client_num: 30
  method: fedprox
fedprox:
  use: true
  mu: 0.1
data:
  root: data/
  type: subreddit
  subsample: 1.0
dataloader:
  batch_size: 5
model:
  type: lstm
  in_channels: 10000
  out_channels: 10000
  hidden: 256
  embed_size: 200
  dropout: 0.0
train:
  local_update_steps: 10
  optimizer:
    lr: 8.0
    weight_decay: 0.0
criterion:
  type: CrossEntropyLoss
trainer:
  type: nlptrainer
eval:
  freq: 1
  metrics: ['acc', 'correct']