use_gpu: True
device: 0
seed: 12345
early_stop:
  patience: 0
federate:
  mode: standalone
  total_round_num: 200
  client_num: 30
  method: fedsak
aggregator:
  lambda_: 5
  lr_shared: 0.05
  filter_keys:                 
  - encoder.weight
  - rnn.weight_ih_l0
  - rnn.weight_hh_l0
  - rnn.bias_ih_l0
  - rnn.bias_hh_l0
  - rnn.weight_ih_l1
  - rnn.weight_hh_l1
  - rnn.bias_ih_l1
  - rnn.bias_hh_l1
  - decoder.weight
  - decoder.bias
fedsak:               
  share_patterns:
  - encoder.weight
  - rnn.weight_ih_l0
  - rnn.weight_hh_l0
  - rnn.bias_ih_l0
  - rnn.bias_hh_l0
  - rnn.weight_ih_l1
  - rnn.weight_hh_l1
  - rnn.bias_ih_l1
  - rnn.bias_hh_l1
  - decoder.weight
  - decoder.bias
fedprox:
  use: false
  mu: 0
data:
  root: data/
  type: subreddit
  subsample: 1.0
dataloader:
  batch_size: 5
model:
  type: lstm
  in_channels: 10000
  out_channels: 10000
  hidden: 256
  embed_size: 200
  dropout: 0.0
train:
  local_update_steps: 10
  optimizer:
    lr: 8.0
    weight_decay: 0.0
criterion:
  type: CrossEntropyLoss
trainer:
  type: fedsak
eval:
  freq: 1
  metrics: ['acc', 'correct']